from youtube_utils import get_video_metadata, get_transcript
from transcript_processor import process_transcript
from logger import log_video_info

def main(video_id):
    # Step 1: Retrieve video metadata and description
    video_metadata = get_video_metadata(video_id)
    
    # Step 2: Get autogenerated transcript
    transcript = get_transcript(video_id)
    
    # Step 3: Process transcript (time-segmented)
    processed_transcript = process_transcript(transcript)
    
    # Step 4: Log the information
    log_video_info(video_metadata, processed_transcript)
    
if __name__ == "__main__":
    # Example video ID
    video_id = "YOUR_VIDEO_ID_HERE"
    main(video_id) 