"""add_timestamp_fields

Revision ID: 13219d89f5dd
Revises: e8410f31a889
Create Date: 2024-12-07 10:33:14.374894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13219d89f5dd'
down_revision: Union[str, None] = 'e8410f31a889'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('channels', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('highlights', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('highlights', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('videos', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('videos', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'updated_at')
    op.drop_column('videos', 'created_at')
    op.drop_column('highlights', 'updated_at')
    op.drop_column('highlights', 'created_at')
    op.drop_column('channels', 'updated_at')
    op.drop_column('channels', 'created_at')
    # ### end Alembic commands ###
