"""Add prompt system_role review_comment columns to highlights

Revision ID: 161d8e22e258
Revises: bb2f498c9cc5
Create Date: 2024-12-10 21:39:54.038005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '161d8e22e258'
down_revision: Union[str, None] = 'bb2f498c9cc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('highlights', sa.Column('review_comment', sa.Text(), nullable=True))
    op.drop_column('highlights', 'comment')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('highlights', sa.Column('comment', sa.TEXT(), nullable=True))
    op.drop_column('highlights', 'review_comment')
    # ### end Alembic commands ###
