"""add_review_status_to_highlights

Revision ID: 625861e6d69f
Revises: xxx
Create Date: 2024-12-07 21:07:27.482150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '625861e6d69f'
down_revision: Union[str, None] = 'xxx'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('highlights', sa.Column('review_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('highlights', 'review_status')
    # ### end Alembic commands ###
