"""Add prompt, system_role, and comment columns to highlights

Revision ID: bb2f498c9cc5
Revises: 625861e6d69f
Create Date: 2024-12-10 21:24:22.321789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb2f498c9cc5'
down_revision: Union[str, None] = '625861e6d69f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('highlights', sa.Column('prompt', sa.Text(), nullable=True))
    op.add_column('highlights', sa.Column('system_role', sa.Text(), nullable=True))
    op.add_column('highlights', sa.Column('comment', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('highlights', 'comment')
    op.drop_column('highlights', 'system_role')
    op.drop_column('highlights', 'prompt')
    # ### end Alembic commands ###
