"""check model changes

Revision ID: bf61a1012716
Revises: 
Create Date: 2024-12-05 19:34:18.436974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf61a1012716'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcripts', sa.Column('raw_transcript', sa.Text(), nullable=True))
    op.add_column('transcripts', sa.Column('processed_transcript', sa.Text(), nullable=True))
    op.drop_column('transcripts', 'processing_status')
    op.drop_column('transcripts', 'processed_content')
    op.drop_column('transcripts', 'raw_content')
    op.add_column('videos', sa.Column('processing_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'processing_status')
    op.add_column('transcripts', sa.Column('raw_content', sa.TEXT(), nullable=True))
    op.add_column('transcripts', sa.Column('processed_content', sa.TEXT(), nullable=True))
    op.add_column('transcripts', sa.Column('processing_status', sa.VARCHAR(), nullable=True))
    op.drop_column('transcripts', 'processed_transcript')
    op.drop_column('transcripts', 'raw_transcript')
    # ### end Alembic commands ###
