"""simplify_highlight_model

Revision ID: e8410f31a889
Revises: bf61a1012716
Create Date: 2024-12-06 16:00:32.545504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8410f31a889'
down_revision: Union[str, None] = 'bf61a1012716'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_videos')
    op.create_index(op.f('ix_highlights_id'), 'highlights', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_highlights_id'), table_name='highlights')
    op.create_table('_alembic_tmp_videos',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('channel_id', sa.VARCHAR(), nullable=True),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('duration', sa.INTEGER(), nullable=True),
    sa.Column('processed_at', sa.DATETIME(), nullable=True),
    sa.Column('url', sa.VARCHAR(), nullable=True),
    sa.Column('thumbnail_url', sa.VARCHAR(), nullable=True),
    sa.Column('processing_status', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
